config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :exercises
  end
  root 'workouts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
  
class ExercisesController < ApplicationController
	def create
		@workout = Workout.find(params[:workout_id])
		@exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))

		redirect_to workout_path(@workout)
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :find_workout, only: [:show, :edit, :update, :destroy]
    def index
        @workout = Workout.all.order("created_at DESC")
    end
    def show
        
    end
    def new
        @workout = Workout.new
    end
    def create
        @workout = Workout.new(workouts_params)
        if @workout.save
            redirect_to @workout
        else
            render 'new'
        end
    end
    def edit
        
    end
    def update
        if @workout.update(workouts_params)
            redirect_to @workout
        else
            render 'edit'
        end
    end
    def destroy
        @workout.destroy
        redirect_to root_path
    end

    private

    def workouts_params
        params.require(:workout).permit(:date, :workout, :mood, :length)
    end
    def find_workout
        @workout = Workout.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
%p= exercise.sets
%p= exercise.reps

app/views/exercises/_form.html.haml
= simple_form_for([@workout, @workout.exercises.build]) do |f|
	= f.input :name, input_html: { class: "form-control" }
	= f.input :sets, input_html: { class: "form-control" }
	= f.input :reps, input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Workout Log Application
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-header
				= link_to "Workout Log", root_path, class: "navbar-brand"
			.nav.navbar-nav.navbar-right
				= link_to "New Workout", new_workout_path, class: "nav navbar-link"

	.container
		= yield

app/views/workouts/_form.html.haml
= simple_form_for(@workout, html: { class: 'form-horizontal' }) do |f|
	= f.input :date, label: "Date"
	= f.input :workout, label: "What area did you workout?", input_html: { class: "form-control" }
	= f.input :mood, label: "How were you feeling?", input_html: { class: "form-control" }
	= f.input :length, label: "How long was the workout?", input_html: { class: "form-control" }
	%br/
	= f.button :submit

app/views/workouts/edit.html.haml
%h1 Edit Workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/index.html.haml
#index_workouts
	- @workout.each do |workout|
		%h2= link_to workout.date.strftime("%A %B %d"), workout
		%h3
			%span Workout:
			= workout.workout

app/views/workouts/new.html.haml
%h1 New Workout

= render 'form'

= link_to "Cancel", root_path

app/views/workouts/show.html.haml
  
#workout
	%p= @workout.date
	%p= @workout.workout
	%p= @workout.mood
	%p= @workout.length

#exercises
	%h2 Exercises
	= render @workout.exercises

	%h3 Add an exercise
	= render "exercises/form"

= link_to "Back", root_path
= link_to "Edit", edit_workout_path(@workout)
= link_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" }